
azure:
  activedirectory:
    tenant-id: 5484bd9a-fcc6-4614-95e1-103a68c98ff1
    active-directory-groups: group1, group2

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AD_CLIENT_ID}
            client-secret: ${AD_CLIENT_SECRET}

